### ISSUE TITLE
automatic close the menu when I tap one some menu item?

### ISSUE THREAD

**Issue by aquilx** [pavel-chehov/CircleMenu#7]
Hi friend, I really like your circle-menu is very very cool, I think your design this menu is for push viewcontoller is ok, but I want to tap some menu then popup some alert it will not support. would like to open the close menu function to support that? thank you.

**Comment by pavel-chehov** [comment]
Hi, thanks for your feedback!
You are completely right, I didn't expect this userflow. So, if you need quick hack, you can fork this source code and make changes on it. I think simplest way - add new public function in CircleMenu class, which can emulate close button action
`public func closeMenuOutside() {
        mainButton?.sendActions(for: .touchUpInside)
    }`
It will work for 1st level menu, not for submenus.
It's very quick, but not pretty solution. I need to think about updating CircleMenu api.

**Comment by pavel-chehov** [comment]
I've added required feature. You should set circleMenu.closeByTapOutside = true if you want to close menu by tapping outside of hamburger button.
